version: '3.1'

services:
   db:
      image: postgres
      restart: always
      environment:
         POSTGRES_PASSWORD: trytofindme
      ports:
         - 5432:5432
      networks:
         - dbpostgres

   adminer:
      image: adminer
      restart: always
      ports:
         - 8020:8080
      networks:
         - dbpostgres

networks:
   dbpostgres:
      driver: nat
