export const AC_TEST_REQUEST = 'AC_TEST_REQUEST';
export const AC_TEST_SUCCESS = 'AC_TEST_SUCCESS';
export const AC_TEST_FAILED = 'AC_TEST_FAILED';
export const AC_TEST_GET_RESULTS = 'AC_TEST_GET_RESULTS';
export const AC_TEST_GET_ALL_ANSWERS = 'AC_TEST_GET_ALL_ANSWERS';
export const AC_TEST_GET_TESTINGSYSTEM_TESTS = 'AC_TEST_GET_TESTINGSYSTEM_TESTS';
