export const DS_TEST_REQUEST = 'DS_TEST_REQUEST';
export const DS_TEST_SUCCESS = 'DS_TEST_SUCCESS';
export const DS_TEST_FAILED = 'DS_TEST_FAILED';
export const DS_TEST_GET_RESULTS = 'DS_TEST_GET_RESULTS';
export const DS_TEST_GET_ALL_ANSWERS = 'DS_TEST_GET_ALL_ANSWERS';
export const DS_TEST_GET_TESTINGSYSTEM_TESTS = 'DS_TEST_GET_TESTINGSYSTEM_TESTS';
