export const MDT_TEST_REQUEST = 'MDT_TEST_REQUEST';
export const MDT_TEST_SUCCESS = 'MDT_TEST_SUCCESS';
export const MDT_TEST_FAILED = 'MDT_TEST_FAILED';
export const MDT_TEST_GET_RESULTS = 'MDT_TEST_GET_RESULTS';
export const MDT_TEST_GET_ALL_ANSWERS = 'MDT_TEST_GET_ALL_ANSWERS';
