export const PSSUQ_TEST_REQUEST = 'PSSUQ_TEST_REQUEST';
export const PSSUQ_TEST_SUCCESS = 'PSSUQ_TEST_SUCCESS';
export const PSSUQ_TEST_FAILED = 'PSSUQ_TEST_FAILED';
export const PSSUQ_TEST_GET_RESULTS = 'PSSUQ_TEST_GET_RESULTS';
export const PSSUQ_TEST_GET_ALL_ANSWERS = 'PSSUQ_TEST_GET_ALL_ANSWERS';
