export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const REGISTRATION_GET_ID_REQUEST = "REGISTRATION_GET_ID_REQUEST";
export const REGISTRATION_GET_ID_SUCCESS = "REGISTRATION_GET_ID_SUCCESS";
export const REGISTRATION_GET_ID_FAILED = "REGISTRATION_GET_ID_FAILED";