export const SHT_TEST_REQUEST = 'SHT_TEST_REQUEST';
export const SHT_TEST_SUCCESS = 'SHT_TEST_SUCCESS';
export const SHT_TEST_FAILED = 'SHT_TEST_FAILED';
export const SHT_TEST_GET_RESULTS = 'SHT_TEST_GET_RESULTS';
export const SHT_TEST_GET_ALL_ANSWERS = 'SHT_TEST_GET_ALL_ANSWERS';
export const SHT_TEST_GET_TESTINGSYSTEM_TESTS = 'SHT_TEST_GET_TESTINGSYSTEM_TESTS';
